BEGIN{
txt2mc["A"] = ".-"
txt2mc["B"] = "-..."
txt2mc["C"] = "-.-."
txt2mc["D"] = "-.."
txt2mc["E"] = "."
txt2mc["F"] = "..-."
txt2mc["G"] = "--."
txt2mc["H"] = "...."
txt2mc["I"] = ".."
txt2mc["J"] = ".---"
txt2mc["K"] = "-.-"
txt2mc["L"] = ".-.."
txt2mc["M"] = "--"
txt2mc["N"] = "-."
txt2mc["O"] = "---"
txt2mc["P"] = ".--."
txt2mc["Q"] = "--.-"
txt2mc["R"] = ".-."
txt2mc["S"] = "..."
txt2mc["T"] = "-"
txt2mc["U"] = "..-"
txt2mc["V"] = "...-"
txt2mc["W"] = ".--"
txt2mc["X"] = "-..-"
txt2mc["Y"] = "-.--"
txt2mc["Z"] = "--.."
txt2mc["0"] = "-----"
txt2mc["1"] = ".----"
txt2mc["2"] = "..---"
txt2mc["3"] = "...--"
txt2mc["4"] = "....-"
txt2mc["5"] = "....."
txt2mc["6"] = "-...."
txt2mc["7"] = "--..."
txt2mc["8"] = "---.."
txt2mc["9"] = "----."
txt2mc["."] = ".-.-.-"
txt2mc[","] = "--..--"
txt2mc["?"] = "..--.."
txt2mc["-"] = "-....-"
txt2mc["/"] = "-..-."
txt2mc[":"] = "---..."
txt2mc["'"] = ".----."
txt2mc["-"] = "-....-"
txt2mc[")"] = "-.--.-"
txt2mc[";"] = "-.-.-"
txt2mc["("] = "-.--."
txt2mc["="] = "-...-"
txt2mc["@"] = ".--.-."

mc2txt[".-"]="A"
mc2txt["-..."]="B"
mc2txt["-.-."]="C"
mc2txt["-.."]="D"
mc2txt["."]="E"
mc2txt["..-."]="F"
mc2txt["--."]="G"
mc2txt["...."]="H"
mc2txt[".."]="I"
mc2txt[".---"]="J"
mc2txt["-.-"]="K"
mc2txt[".-.."]="L"
mc2txt["--"]="M"
mc2txt["-."]="N"
mc2txt["---"]="O"
mc2txt[".--."]="P"
mc2txt["--.-"]="Q"
mc2txt[".-."]="R"
mc2txt["..."]="S"
mc2txt["-"]="T"
mc2txt["..-"]="U"
mc2txt["...-"]="V"
mc2txt[".--"]="W"
mc2txt["-..-"]="X"
mc2txt["-.--"]="Y"
mc2txt["--.."]="Z"
mc2txt["-----"]="0"
mc2txt[".----"]="1"
mc2txt["..---"]="2"
mc2txt["...--"]="3"
mc2txt["....-"]="4"
mc2txt["....."]="5"
mc2txt["-...."]="6"
mc2txt["--..."]="7"
mc2txt["---.."]="8"
mc2txt["----."]="9"
mc2txt[".-.-.-"]="."
mc2txt["--..--"]=","
mc2txt["..--.."]="?"
mc2txt["-....-"]="-"
mc2txt["-..-."]="/"
mc2txt["---..."]=":"
mc2txt[".----."]="'"
mc2txt["-....-"]="-"
mc2txt["-.--.-"]=")"
mc2txt["-.-.-"]=";"
mc2txt["-.--."]="("
mc2txt["-...-"]="="
mc2txt[".--.-."]="@"


}{
	if( NF > 0 )
		printf( mc2txt[$1] )
	else
		printf( " " )
}END{
	print ""
}

